#!/bin/bash
echo "Building cop.js"

cd js/core
cat _cop.js hashtable.js hashset.js subject.js policy.js contextregistry.js contextmanager.js context.js combinedcontext.js trait.js > ../../cop.js

cd ../traits
cat traits-for-cop.js >> ../../cop.js

echo "cop.load()" >> ../../cop.js

cd ../../
echo "Done."

echo "Minifying cop.js -> cop-min.js"
jsmin < cop.js > cop-min.js

echo "Done."

echo "Updata example projects with latest cop.js"
cp cop.js examples/jquerymobile/_attachments/script/

echo "Done."
